spring:
  datasource:
    url: jdbc:mysql://39.105.186.116:3306/cboard?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    name: CBoard Meta Data
    username: root
    password: ''

#logging:
#  level: debug